import type { CatalogRecord } from './_forms-catalog.js';

// California assessment-appeal registry. Unlike TX/GA/FL there is NO usable
// statewide PDF: LA renumbers the form as AAB-100, and Alameda deems an
// application on a prior revision INVALID. So every CA record is county-specific,
// `delivery` is 'official' (county URL primary, our mirror is only a fallback),
// and an uncovered county gets no PDF at all.
//
// Coverage: 53 counties. The original 5 (Los Angeles, San Francisco,
// Sacramento, Alameda, Contra Costa) were verified 2026-07-20 and have a
// mirrored PDF; the other 48 were added 2026-07-21 from each county's own
// clerk-of-the-board site and carry NO mirror (`pdfPath: ''`) — CA delivery
// is 'official', so the county's own URL is the primary download either way.
// Eight of those 48 (Sonoma, Tulare, Monterey, Placer, Marin, Santa Barbara,
// Santa Cruz, Solano) were held back from the initial batch pending an
// independent re-check of their fee and mailing address; that re-check
// completed 2026-07-21 and they now ship. Marin's mailTo and Santa Barbara's
// fee were corrected during that pass — see their `notes`.
//
// Santa Clara is deliberately absent: every county host is behind a Cloudflare
// bot challenge, so its form URL, fee and mailing address could not be
// verified. It falls through to CA_FORM_FALLBACK, which still gives it the
// BOE-certified Sept 15 deadline. Do not add it from secondary sources.
//
// Deadlines split on whether the county Assessor mails value notices — see
// CA_SEPT15 / caDeadline() below, which cover all 58 counties.

export interface CaCounty {
  form: string;
  formTitle: string;
  /** Our mirror. Empty string = not mirrored; the official county URL is primary. */
  pdfPath: string;
  officialUrl: string;
  authority: string;
  efileUrl: string | null;
  website: string;
  mailTo: string;
  deadline: string;
  fee: string | null;   // null = no filing fee
  paperOnly?: boolean;
  notes: string[];
  verifiedOn: string;
  /**
   * Optional bespoke "how to VIEW the assessor's evidence" text. When absent the
   * UI renders its per-state default. In CA the assessor must furnish the
   * comparable-sales data behind your value on request (R&T §408/§1606).
   */
  evidenceHowTo?: string;
}

export const CA_COUNTIES: Record<string, CaCounty> = {
  losangeles: {
    form: 'AAB-100',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '/forms/ca-losangeles-aab-100.pdf',
    // Current rev 12 (05-24), linked from bos.lacounty.gov. The copy at
    // lacaab.lacounty.gov/helpfiles/forms/AAB100.pdf is a stale 2011 version.
    officialUrl: 'https://assets-us-01.kc-usercontent.com/0234f496-d2b7-00b6-17a4-b43e949b70a2/06e3a7ca-2764-4717-ac77-f04b930e1a7d/Fillable%20Form%20AAB100%20for%20website%20rev%2012%20%2805-24%29%20FINAL.pdf',
    authority: 'Assessment Appeals Board, County of Los Angeles',
    efileUrl: 'https://lacaab.lacounty.gov/Home.aspx',
    website: 'https://bos.lacounty.gov/services/assessment-appeals/',
    // Room B4 is what's printed on the form for filing (not Room 383).
    mailTo: 'Assessment Appeals Board, Kenneth Hahn Hall of Administration, 500 West Temple St., Room B4, Los Angeles, CA 90012',
    deadline: 'July 2 – November 30',
    fee: '$46',
    notes: ['Los Angeles uses its own AAB-100 version of the state application.'],
    verifiedOn: '2026-07-20',
  },
  sanfrancisco: {
    form: 'BOE-305-AH',
    formTitle: 'Application for Changed Assessment',
    pdfPath: '/forms/ca-sanfrancisco-boe-305-ah.pdf',
    officialUrl: 'https://media.api.sf.gov/documents/ApplicationForm-8-1-25.pdf',
    authority: 'Assessment Appeals Board, City and County of San Francisco',
    // SF's online portal URL is not published while the portal is closed
    // (reopens 2026-07-22). Never guess it.
    efileUrl: null,
    website: 'https://www.sf.gov/departments--assessment-appeals-board',
    mailTo: 'Assessment Appeals Board, 1 Dr. Carlton B. Goodlett Place, City Hall, Room 405, San Francisco, CA 94102',
    deadline: 'July 2 – September 15',
    fee: '$120',
    notes: [],
    verifiedOn: '2026-07-20',
  },
  sacramento: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '/forms/ca-sacramento-boe-305-ah.pdf',
    officialUrl: 'https://sccob.saccounty.gov/content/dam/sccob/documents/assesmentappeals/AAB_Appl+Instr.pdf',
    authority: 'Sacramento County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://sccob.saccounty.gov/content/sccob/us/en/assessment-appeals.html',
    mailTo: 'Assessment Appeals Board, 700 H Street, Suite 2450, Sacramento, CA 95814',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: ['Sacramento accepts paper applications only — you must mail an original, signed form.'],
    verifiedOn: '2026-07-20',
  },
  alameda: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '/forms/ca-alameda-boe-305-ah.pdf',
    officialUrl: 'https://www.acgov.org/clerk/forms/2026AssessmentAppealApplication_BOE-305AHP1REV1205-24REV2.pdf',
    authority: 'Alameda County Assessment Appeals Board',
    efileUrl: 'https://aab.alamedacountyca.gov',
    website: 'https://www.acgov.org/clerk/assessment.htm',
    mailTo: 'Alameda County Assessment Appeals Board, 1221 Oak St., Suite 536, Oakland, CA 94612',
    deadline: 'July 2 – September 15',
    fee: '$50',
    notes: [
      'Alameda requires the current version of the application — an application on a previous version is deemed invalid, so download it from the county directly.',
      'Paper applications must be completed in duplicate.',
    ],
    verifiedOn: '2026-07-20',
  },
  contracosta: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '/forms/ca-contracosta-boe-305-ah.pdf',
    officialUrl: 'https://www.contracosta.ca.gov/DocumentCenter/View/68174/Assessment-Appeals-Application-Form-',
    authority: 'Contra Costa County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.contracosta.ca.gov/2924/Assessment-Appeals',
    mailTo: 'Assessment Appeals Board, 1025 Escobar Street, 1st Floor (Suite 150), Martinez, CA 94553',
    deadline: 'July 2 – November 30',
    fee: '$40',
    notes: ['Make the filing fee payable to the Contra Costa County Treasurer.'],
    verifiedOn: '2026-07-20',
  },
  alpine: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.alpinecountyca.gov/DocumentCenter/View/75/Assessment-Appeal-Application/',
    authority: 'Alpine County Board of Equalization',
    efileUrl: null,
    website: 'https://www.alpinecountyca.gov',
    mailTo: 'PO Box 158, Markleeville, CA 96120',
    deadline: 'July 2 – September 15',
    fee: '$30',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  amador: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.amadorcounty.gov/home/showpublisheddocument/10061/636694118506470000',
    authority: 'Amador County Board of Equalization',
    efileUrl: null,
    website: 'https://www.amadorcounty.gov',
    mailTo: '810 Court Street, Jackson, CA 95642',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: ['Ships the 2015 BOE-305-AH revision - the most stale form found in CA.'],
    verifiedOn: '2026-07-21',
  },
  butte: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.buttecounty.net/DocumentCenter/View/19314/2026-27-Assessment-Appeal-Application',
    authority: 'Clerk of the Assessment Appeals Board, Butte County',
    efileUrl: null,
    website: 'https://www.buttecounty.net',
    mailTo: 'Clerk of the Assessment Appeals Board, 25 County Center Drive, Suite 200, Oroville, CA 95965',
    deadline: 'July 2 – November 30',
    fee: '$40',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  calaveras: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://bos.calaverasgov.us/Portals/BOS/Documents/Assessment%20Appeals/2025%20AAB%20application%20305ah-rev12%2005-24.pdf',
    authority: 'Calaveras County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://bos.calaverasgov.us',
    mailTo: '891 Mountain Ranch Rd., San Andreas, CA 95249',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED.'],
    verifiedOn: '2026-07-21',
  },
  colusa: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.countyofcolusaca.gov/DocumentCenter/View/18178/Assessment-Appeal-Application-Rev-05-22',
    authority: 'Colusa County Clerk of the Board',
    efileUrl: null,
    website: 'https://www.countyofcolusaca.gov',
    mailTo: '547 Market St., Ste 102, Colusa, CA 95932',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED. Ships stale rev.11.'],
    verifiedOn: '2026-07-21',
  },
  eldorado: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.eldoradocounty.ca.gov/files/assets/county/v/1/documents/government/bos/clerk-of-the-board/assessment-appeals/aab-forms/application-form-and-instructions-2025-boe-305-ah-rev.-12-05-24.pdf',
    authority: 'El Dorado County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.eldoradocounty.ca.gov',
    mailTo: 'Clerk of the Board of Supervisors, 330 Fair Lane, Building A, Placerville, CA 95667',
    deadline: 'July 2 – November 30',
    fee: '$40',
    paperOnly: true,
    notes: [
      'PDF body UNVERIFIED - county WAF blocks direct retrieval. Link confirmed live on official page.',
    ],
    verifiedOn: '2026-07-21',
  },
  fresno: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.fresnocountyca.gov/files/sharedassets/county/v/5/clerk-of-the-board/assessment-appeals/2025-aab-application.pdf',
    authority: 'Fresno County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.fresnocountyca.gov',
    mailTo: 'Clerk of the Board of Supervisors, Hall of Records, 2281 Tulare Street, Room 301, Fresno, CA 93721',
    deadline: 'July 2 – November 30',
    fee: '$86',
    paperOnly: true,
    notes: ['Original wet signature required; no email or fax.'],
    verifiedOn: '2026-07-21',
  },
  humboldt: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://humboldtgov.org/DocumentCenter/View/55825/Property-Assessment-Appeal-Application',
    authority: 'Humboldt County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://humboldtgov.org',
    mailTo: 'Clerk of the Board, 825 Fifth Street, Room 111, Eureka, CA 95501',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Form is older REV. 08 (01-15). No fee stated anywhere; affirmative \'no fee\' UNVERIFIED.'],
    verifiedOn: '2026-07-21',
  },
  imperial: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://board.imperialcounty.org/wp-content/uploads/2025/11/Application-for-Changed-Assessment.pdf',
    authority: 'Clerk of the Board of Supervisors, County of Imperial',
    efileUrl: null,
    website: 'https://board.imperialcounty.org',
    mailTo: 'County of Imperial, Clerk of the Board, 940 Main Street, Suite 209, El Centro, CA 92243',
    deadline: 'July 2 – November 30',
    fee: '$35',
    paperOnly: true,
    notes: ['Form is older REV. 08 (01-15). Faxed applications NOT accepted.'],
    verifiedOn: '2026-07-21',
  },
  inyo: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.inyocounty.us/sites/default/files/2025-09/Application%20for%20Changed%20Assessment%20-%20Inyo%20County%20%28updated%205.25%29_0.pdf',
    authority: 'Inyo County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.inyocounty.us',
    mailTo: 'P.O. Drawer N, Independence, CA 93526',
    deadline: 'July 2 – September 15',
    fee: '$32',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  kern: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.kerncounty.com/home/showpublisheddocument/480/638938080680400000',
    authority: 'Kern County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.kerncounty.com',
    mailTo: 'Clerk of the Board, 1115 Truxtun Avenue, 5th Floor, Bakersfield, CA 93301-4617',
    deadline: 'July 2 – November 30',
    fee: '$75',
    paperOnly: true,
    notes: ['Nov 30 confirmed independently by BOE LTA 2026/023; secondary sources wrongly say Sept 15.'],
    verifiedOn: '2026-07-21',
  },
  kings: {
    form: 'Assessment Appeal Application',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.countyofkingsca.gov/home/showpublisheddocument/37738/638853126626430000',
    authority: 'Kings County Board of Equalization',
    efileUrl: null,
    website: 'https://www.countyofkingsca.gov',
    mailTo: 'Clerk of the Board, 1400 W. Lacey Boulevard, Hanford, CA 93230',
    deadline: 'July 2 – September 15',
    fee: '$200 hearing deposit — WAIVED for owner-occupied single-family dwellings',
    paperOnly: true,
    notes: [
      'Form number UNVERIFIED (WAF). Sibling forms are county-numbered, so a county variant is plausible.',
    ],
    verifiedOn: '2026-07-21',
  },
  lake: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://lakecountyca.gov/DocumentCenter/View/4352/Assessment-Appeal-Application-PDF',
    authority: 'Lake County Clerk of the Board',
    efileUrl: null,
    website: 'https://lakecountyca.gov',
    mailTo: '255 N. Forbes Street, Lakeport, CA 95453',
    deadline: 'July 2 – November 30',
    fee: '$35 residential',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  lassen: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.lassencounty.gov/DocumentCenter/View/1357/Assessment-Appeal-Application-PDF',
    authority: 'Lassen County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.lassencounty.gov',
    mailTo: '220 S Lassen St, Suite 5, Susanville, CA 96130',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED (none printed). Suite number differs between form and web page.'],
    verifiedOn: '2026-07-21',
  },
  madera: {
    form: 'Assessment Appeal Application',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.maderacounty.com/home/showpublisheddocument/154/638835071783430000',
    authority: 'Madera County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.maderacounty.com',
    mailTo: 'County of Madera Assessment Appeals Board, 200 W. 4th Street, Madera, CA 93637',
    deadline: 'July 2 – November 30',
    fee: '$200 hearing fee — waived for owner-occupied homes where the owner represents themselves',
    paperOnly: true,
    notes: ['Form number UNVERIFIED (WAF). Copy of tax bill required with application.'],
    verifiedOn: '2026-07-21',
  },
  marin: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://assets.marincounty.gov/marincounty-prod/public/2025-09/Assessment%20Appeal%20Application.pdf',
    authority: 'Marin County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.marincounty.gov/departments/board/appeal-your-property-tax-assessment/assessment-appeal-application',
    mailTo: 'Assessment Appeals Board Clerk, County of Marin, 3501 Civic Center Dr., Ste 329, San Rafael, CA 94903-4193',
    deadline: 'July 2 – November 30',
    fee: '$50',
    paperOnly: true,
    notes: ['Address corrected 2026-07-21 from the form itself; the county contact block omits Ste 329 and ZIP+4.'],
    verifiedOn: '2026-07-21',
  },
  mariposa: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.mariposacounty.gov/DocumentCenter/View/1656/Assessment-Appeal-Form',
    authority: 'Mariposa County Board of Equalization',
    efileUrl: null,
    website: 'https://www.mariposacounty.gov',
    mailTo: 'P.O. Box 784, Mariposa, CA 95338',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  mendocino: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.mendocinocounty.gov/home/showpublisheddocument/75795/639045872994870000',
    authority: 'Mendocino County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.mendocinocounty.gov',
    mailTo: '501 Low Gap Road, Room 1010, Ukiah, CA 95482',
    deadline: 'July 2 – November 30',
    fee: '$150',
    paperOnly: true,
    notes: ['Fee effective 2026-02-14; cached figures are stale.'],
    verifiedOn: '2026-07-21',
  },
  merced: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.countyofmerced.com/DocumentCenter/View/3487',
    authority: 'Merced County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.countyofmerced.com',
    mailTo: 'Merced County Assessment Appeals Board, 2222 M Street, Third Floor, Merced, CA 95340',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  modoc: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.countyofmodoc.gov/DocumentCenter/View/1330',
    authority: 'Modoc County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.countyofmodoc.gov',
    mailTo: '204 S. Court Street, Suite 204, Alturas, CA 96101',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: ['Form is stale REV. 08 (01-15). County migrated domain from co.modoc.ca.us.'],
    verifiedOn: '2026-07-21',
  },
  mono: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.monocounty.ca.gov/sites/default/files/fileattachments/assessor/page/6602/boe_appeal_application_mono_.pdf',
    authority: 'Mono County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.monocounty.ca.gov',
    mailTo: 'P.O. Box 237, Bridgeport, CA 93517',
    deadline: 'July 2 – September 15',
    fee: '$23',
    paperOnly: true,
    notes: [
      'CONFLICT: assessor page says PO Box 456, form says PO Box 237. Used the form. Needs phone confirm.',
    ],
    verifiedOn: '2026-07-21',
  },
  monterey: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.countyofmonterey.gov/home/showpublisheddocument/140437/638835095137430000',
    authority: 'Monterey County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.countyofmonterey.gov',
    mailTo: 'P.O. Box 1728, Salinas, CA 93902-1728',
    deadline: 'July 2 – November 30',
    fee: '$40',
    paperOnly: true,
    notes: ['Fee is web-page-sourced only — the posted application is the plain BOE-305-AH with no county overprint.'],
    verifiedOn: '2026-07-21',
  },
  napa: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.napacounty.gov/DocumentCenter/View/32586/Assessment-Appeal-Application-PDF',
    authority: 'Napa County Clerk of the Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.napacounty.gov',
    mailTo: 'Napa County Clerk of the Assessment Appeals Board, 1195 Third Street, Suite 310, Napa, CA 94559',
    deadline: 'July 2 – November 30',
    fee: '$75 residential',
    paperOnly: true,
    notes: ['An older packet at /DocumentCenter/View/2933 says $50 - STALE, do not use.'],
    verifiedOn: '2026-07-21',
  },
  nevada: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.nevadacountyca.gov/DocumentCenter/View/13663/Assessment-Appeal-Application-PDF',
    authority: 'Nevada County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.nevadacountyca.gov',
    mailTo: 'PO Box 599002, Nevada City, CA 95959',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  orange: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://cob.oc.gov/sites/cob/files/2025-11/Assessment%20Appeal%20Application%20Form%20Fill-In%20305ah-rev07-21-2025_0.pdf',
    authority: 'Clerk of the Board, Assessment Appeals Division, County of Orange',
    efileUrl: 'https://assessmentappeals.ocgov.com/',
    website: 'https://cob.oc.gov',
    mailTo: 'Clerk of the Board, Assessment Appeals Division, 400 W. Civic Center Dr., Room 110, Santa Ana, CA 92701',
    deadline: 'July 2 – November 30',
    fee: null,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  placer: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.placer.ca.gov/DocumentCenter/View/81686/2024-25-Assessment-Appeal-Application_PC-Info',
    authority: 'Placer County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.placer.ca.gov',
    mailTo: 'Placer County Assessment Appeals Board, 175 Fulweiler Avenue, Auburn, CA 95603-4543',
    deadline: 'July 2 – September 15',
    fee: '$40',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  plumas: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.plumascounty.us/DocumentCenter/View/12418',
    authority: 'Plumas County Board of Equalization',
    efileUrl: null,
    website: 'https://www.plumascounty.us',
    mailTo: '520 Main Street, Room 309, Quincy, CA 95971',
    deadline: 'July 2 – November 30',
    fee: '$35',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  riverside: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://rivcocob.org/sites/g/files/aldnop311/files/2024-06/2024-2025_BOE_305_AH_REV_12_(6-24).pdf',
    authority: 'Riverside County Clerk of the Board, Assessment Appeals Division',
    efileUrl: 'https://aao.countyofriverside.us/',
    website: 'https://rivcocob.org',
    mailTo: 'Clerk of the Board, P.O. Box 1628, Riverside, CA 92502-1628',
    deadline: 'July 2 – November 30',
    fee: '$30',
    notes: [
      'PDF is the 2024-25 posting; newer form UNVERIFIED (site behind Cloudflare). Fee from that form.',
    ],
    verifiedOn: '2026-07-21',
  },
  sanbenito: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.sanbenitocountyca.gov/home/showpublisheddocument/13622/638745422200630000',
    authority: 'San Benito County Clerk of the Board',
    efileUrl: null,
    website: 'https://www.sanbenitocountyca.gov',
    mailTo: '481 Fourth Street, 1st Floor, Hollister, CA 95023',
    deadline: 'July 2 – November 30',
    fee: '$45',
    paperOnly: true,
    notes: [
      'Must file via Certified US Mail. A $500 Findings deposit is ambiguous - may be at filing or at hearing. Only the $45 is confirmed on the form.',
    ],
    verifiedOn: '2026-07-21',
  },
  sanbernardino: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://assessmentappeals.cob.sbcounty.gov/docs/SBC_AA_App_2025_Application_Instructions.pdf',
    authority: 'Clerk of the Board of Supervisors, County of San Bernardino',
    efileUrl: 'https://assessmentappeals.cob.sbcounty.gov/NewAppeal.aspx',
    website: 'https://cob.sbcounty.gov',
    mailTo: 'Clerk of the Board of Supervisors, 385 N. Arrowhead Avenue, Second Floor, San Bernardino, CA 92415-0130',
    deadline: 'July 2 – November 30',
    fee: '$45',
    notes: [],
    verifiedOn: '2026-07-21',
  },
  sandiego: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.sandiegocounty.gov/content/dam/sdc/cob/aab/aabadobeapp.pdf',
    authority: 'Clerk of the Board of Supervisors, Assessment Appeals',
    efileUrl: null,
    website: 'https://www.sandiegocounty.gov/content/sdc/cob/aab.html',
    mailTo: 'Clerk of the Board of Supervisors, Assessment Appeals, 1600 Pacific Highway, Room 402, San Diego, CA 92101-2471',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  sanjoaquin: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.sjgov.org/docs/default-source/clerk-of-the-board-documents/assessment-appeals/forms/assessment-appeal-application.pdf?sfvrsn=71275008_5',
    authority: 'San Joaquin County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.sjgov.org',
    mailTo: 'Clerk of the Board, San Joaquin County, 44 N. San Joaquin St., Sixth Floor, Suite 627, Stockton, CA 95202',
    deadline: 'July 2 – November 30',
    fee: '$30 — exempt for owner-occupied homes assessed at $150,000 or less',
    paperOnly: true,
    notes: ['Built on BOE-305-AH REV. 08 (01-15), 11 years stale.'],
    verifiedOn: '2026-07-21',
  },
  sanluisobispo: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.slocounty.ca.gov/departments/administrative-office/forms-documents/clerk-of-the-board/assessment-appeals/forms/assessment-appeal-application-form-(boe-305-ah)',
    authority: 'Clerk of the Assessment Appeals Board, County of San Luis Obispo',
    efileUrl: null,
    website: 'https://www.slocounty.ca.gov',
    mailTo: 'Assessment Appeals Board Clerk, 1055 Monterey St, Suite D430, San Luis Obispo, CA 93408',
    deadline: 'July 2 – September 15',
    fee: '$66',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  sanmateo: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://sanmateotax.my.site.com/AAB/s/appeal-forms',
    authority: 'County of San Mateo Assessment Appeals Board',
    efileUrl: 'https://sanmateotax.my.site.com/AAB',
    website: 'https://sanmateotax.my.site.com/AAB',
    mailTo: 'County of San Mateo Assessment Appeals Board, 500 County Center, 5th Floor, BOS 104, Redwood City, CA 94063',
    deadline: 'July 2 – November 30',
    fee: '$30',
    notes: [
      'Form URL is an opaque Salesforce media ID - pointed at the Appeal Forms PAGE instead of a hardcoded PDF. Legacy smcgov.org copy is the STALE 2023 form.',
    ],
    verifiedOn: '2026-07-21',
  },
  santabarbara: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://content.civicplus.com/api/assets/ca-santabarbaracounty/7da15d67-5444-43db-b77f-472812c5c886?cache=1800',
    authority: 'Santa Barbara County Assessment Appeals Board',
    efileUrl: 'https://sbaaefile.azurewebsites.net/',
    website: 'https://www.countyofsb.org',
    mailTo: 'County of Santa Barbara Clerk of the Board, 105 E. Anapamu Street, Room 407, Santa Barbara, CA 93101',
    deadline: 'July 2 – November 30',
    fee: '$65 per parcel — $1,000 for parcels assessed over $30,000,000',
    notes: [],
    verifiedOn: '2026-07-21',
  },
  santacruz: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.santacruzcountyca.gov/Portals/0/County/COB/24-25%20AAB%20Application.pdf',
    authority: 'Clerk of the Assessment Appeals Board, County of Santa Cruz',
    efileUrl: 'https://www2.santacruzcountyca.gov/AAB/',
    website: 'https://www.santacruzcountyca.gov',
    mailTo: 'Clerk of the Board, 701 Ocean Street, Room 520, Santa Cruz, CA 95060',
    deadline: 'July 2 – November 30',
    fee: '$50',
    notes: ['County page still prints the 2024 filing window and the form is titled "24-25"; fee and address verified current.'],
    verifiedOn: '2026-07-21',
  },
  shasta: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.shastacounty.gov/media/62801',
    authority: 'Shasta County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.shastacounty.gov',
    mailTo: '1450 Court St., Suite 308B, Redding, CA 96001',
    deadline: 'July 2 – November 30',
    fee: '$263',
    paperOnly: true,
    notes: ['Highest fee in CA - verified page-stated, not a typo. Wet ink required.'],
    verifiedOn: '2026-07-21',
  },
  sierra: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.sierracounty.ca.gov/DocumentCenter/View/7633/Assessment-Appeal-Application',
    authority: 'Sierra County Board of Equalization',
    efileUrl: null,
    website: 'https://www.sierracounty.ca.gov',
    mailTo: 'Clerk of the Board, 100 Courthouse Square Rm 11, PO Drawer D, Downieville, CA 95936',
    deadline: 'July 2 – September 15',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED. Form is bare statewide BOE-305-AH with no county header.'],
    verifiedOn: '2026-07-21',
  },
  solano: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://content.solanocounty.gov/sites/default/files/2025-07/Assessment_Appeals_Application_2025.pdf',
    authority: 'Solano County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.solanocounty.gov',
    mailTo: 'Solano County Board of Supervisors, 675 Texas Street, Suite 6500, Fairfield, CA 94533',
    deadline: 'July 2 – November 30',
    fee: '$35 per parcel',
    paperOnly: true,
    notes: ['Current form is the 2025 file; no 2026 version posted yet. Fee and address verified.'],
    verifiedOn: '2026-07-21',
  },
  sonoma: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://sonomacounty.gov/Main%20County%20Site/Administrative%20Support%20%26%20Fiscal%20Services/BoS/Documents/Assessment%20Appeals/AAB-Application-Instructions.pdf',
    authority: 'Assessment Appeals Board, County of Sonoma',
    efileUrl: null,
    website: 'https://sonomacounty.gov',
    mailTo: 'Assessment Appeals Board, County of Sonoma, 575 Administration Drive, Room 100A, Santa Rosa, CA 95403-2815',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
  stanislaus: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.stancounty.com/board/aab/pdf/aab-application.pdf',
    authority: 'Stanislaus County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.stancounty.com/board/aab/',
    mailTo: 'Clerk of the Board of Supervisors, 1010 10th Street, Suite 6700, Modesto, CA 95354',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: [
      'Plain statewide form with NO county overlay - the mailing address and fee appear only on the webpage, not the form the filer holds.',
    ],
    verifiedOn: '2026-07-21',
  },
  tehama: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.tehama.gov/wp-content/uploads/2025/03/305ah-rev12-05-24.pdf',
    authority: 'Tehama County Board of Equalization',
    efileUrl: null,
    website: 'https://www.tehama.gov',
    mailTo: 'PO Box 250, Red Bluff, CA 96080',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED.'],
    verifiedOn: '2026-07-21',
  },
  trinity: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://trinitycounty.org/DocumentCenter/View/297/Assessment-Appeal-Application-PDF',
    authority: 'Trinity County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://trinitycounty.org',
    mailTo: 'Trinity County Clerk of the Board, 11 Court Street Rm 230, PO Box 1613, Weaverville, CA 96093',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: ['Fee UNVERIFIED.'],
    verifiedOn: '2026-07-21',
  },
  tulare: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://tc-web.widen.net/s/gx2lkjdtlf/assessment-appeals-instructions-and-application-305ah-rev12-05-24',
    authority: 'Tulare County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://tularecounty.ca.gov/clerk-board/assessment-appeals-documents',
    mailTo: 'Clerk of the Board of Supervisors, 2800 W. Burrel Avenue, Visalia, CA 93291-4593',
    deadline: 'July 2 – November 30',
    fee: '$30',
    paperOnly: true,
    notes: ['Fee is web-page-sourced only — no county-overprinted application PDF is published.'],
    verifiedOn: '2026-07-21',
  },
  tuolumne: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.tuolumnecounty.ca.gov/DocumentCenter/View/1807',
    authority: 'Tuolumne County Board of Equalization',
    efileUrl: null,
    website: 'https://www.tuolumnecounty.ca.gov',
    mailTo: '2 S. Green Street, Sonora, CA 95370',
    deadline: 'July 2 – November 30',
    fee: null,
    paperOnly: true,
    notes: [
      'Fee UNVERIFIED. NOTE: a $60 figure circulates on third-party sites INCLUDING taxdrop.com - unverified, do not reuse.',
    ],
    verifiedOn: '2026-07-21',
  },
  ventura: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://vcportal.venturacounty.gov/CEO/COB/assessment-appeals/Assessment%20Appeal%20Application%20BOE-305-AH%20Rev%2012%2005-24%20-%20County%20of%20Ventura.pdf',
    authority: 'Ventura County Assessment Appeals Board',
    efileUrl: 'https://cobpublic.venturacounty.gov/AssessmentAppeals',
    website: 'https://www.venturacounty.gov',
    mailTo: 'Clerk of the Assessment Appeals Board, 800 South Victoria Avenue, #1920, Ventura, CA 93009-1920',
    deadline: 'July 2 – September 15',
    fee: null,
    notes: ['No filing fee (verified by absence). Online filings timely until 11:59pm vs 5pm in person.'],
    verifiedOn: '2026-07-21',
  },
  yolo: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.yolocounty.gov/home/showpublisheddocument/10799/639014013908970000',
    authority: 'Yolo County Clerk of the Board',
    efileUrl: 'https://yolocountyca.seamlessdocs.com/f/e5rmgyqddoju',
    website: 'https://www.yolocounty.gov',
    mailTo: '625 Court Street, Woodland, CA 95695',
    deadline: 'July 2 – November 30',
    fee: '$45',
    notes: ['Online filing adds a $2 service fee.'],
    verifiedOn: '2026-07-21',
  },
  yuba: {
    form: 'BOE-305-AH',
    formTitle: 'Assessment Appeal Application',
    pdfPath: '',
    officialUrl: 'https://www.yuba.gov/Documents/Departments/Departments%20C%20to%20D/Clerk%20of%20the%20Board%20of%20Supervisors/Assessment%20Appeals/305ah-rev12%2005-24.pdf',
    authority: 'Yuba County Assessment Appeals Board',
    efileUrl: null,
    website: 'https://www.yuba.gov',
    mailTo: '915 8th Street, Suite 109, Marysville, CA 95901',
    deadline: 'July 2 – November 30',
    fee: '$35',
    paperOnly: true,
    notes: [],
    verifiedOn: '2026-07-21',
  },
};

export function lookupCaCounty(slug: string): CaCounty | null {
  return CA_COUNTIES[slug] || null;
}

// BOE Letter To Assessors 2026/023 certifies every county's filing deadline under
// R&T §1603. Sept 15 where the Assessor mails value notices to all secured-roll
// taxpayers by Aug 1; otherwise Nov 30. RE-PULL EACH JUNE — counties can switch.
// https://www.boe.ca.gov/proptaxes/pdf/lta26023.pdf
const CA_SEPT15 = new Set<string>([
  'alameda','alpine','inyo','kings','mono','placer','sanfrancisco',
  'sanluisobispo','santaclara','sierra','ventura',
]);

/** Certified filing deadline for ANY California county, covered or not. */
export function caDeadline(slug: string): string {
  return CA_SEPT15.has(slug)
    ? 'July 2 – September 15'
    : 'July 2 – November 30';
}

/**
 * Uncovered CA county. Deliberately carries NO pdfPath: California counties each
 * publish their own application and at least one (Alameda) voids anything else,
 * so handing over a generic form we can't verify is worse than handing over none.
 *
 * The deadline is still exact when we know the county slug: the BOE certifies
 * one for all 58 counties, so an uncovered county gets its real date rather than
 * the "one or the other" hedge.
 */
export function CA_FORM_FALLBACK(slug?: string): CatalogRecord {
  return {
    state: 'CA',
    form: 'Assessment Appeal Application',
    formTitle: 'Application for Changed Assessment',
    pdfPath: null,
    officialUrl: null,
    delivery: 'official',
    authority: 'your county assessment appeals board',
    filing: { efileUrl: null, website: null, mailTo: null, evidenceHowTo: null },
    deadline: slug ? caDeadline(slug) : 'July 2 – September 15 or November 30, depending on your county',
    deadlineAlt: null,
    fee: null,
    paperOnly: false,
    notes: [
      'California counties publish their own appeal application — download the one from your county assessment appeals board, not a generic copy.',
    ],
    verifiedOn: '2026-07-20',
    coverage: 'state',
  };
}
